site_name: Azure Sevilla
site_description: A blog about Azure, DevOps and other stuff
site_author: Rafael Fernández
site_url: https://azuresevilla.github.io

theme: 
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - toc.nested
    - toc.smoothscroll
    - footer
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/8162773/
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/AzureSevilla
      name: GitHub
    - icon: fontawesome/solid/square-rss
      link: https://azuresevilla.github.io/feed_rss_created.xml
      name: RSS feed
  alternate:
      # Original Language
    - name: English
      lang: en
      link: https://azuresevilla-github-io.translate.goog/?_x_tr_sl=auto&_x_tr_tl=es&_x_tr_hl=es&_x_tr_pto=wapp # Google Translate link
      # Extra languages
    - name: Spanish
      lang: es # Language code
      link: https://azuresevilla-github-io.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp # Google Translate link
      # _x_tr_sl = source language
      # _x_tr_tl = translation language
copyright: Copyright &copy; 2024-now Azure Sevilla


plugins:
  - search  
  - mermaid2
  - table-reader
  - blog:
      archive: true
      archive_toc: true
      archive_name: Archive
      archive_date_format: yyyy/MM
      archive_url_date_format: yyyy/MM
      archive_url_format: "{date}"
  - tags:
      tags_file: blog/tags.md
  - rss:
      match_path: blog/posts/.*/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  - glightbox:
      zoomable: true
      draggable: true
      skip_classes:
        - skip-lightbox
    #- meta in insiders, review in next release
  - social

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Blog:
    - blog/index.md
    - blog/tags.md
  - Comunidad: index.md
  - Sponsors: sponsors.md
  - Organizadores: organizers.md
  

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js