authors:
  rfernandezdo:
    name: Rafael Fernández
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/39990341
  jioller:
    name: Juan Ignacio Oller
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/25105615
  